name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: python -m pip install meson ninja
      - name: Install project dependencies (fix sandbox violation later instead)
        run: meson subprojects download
      - name: Configure Project
        run: meson setup builddir/
      - name: Run Tests
        run: meson test -C builddir/ -v
